version: '3.8'

services:
  screenshot-api:
    build: .
    container_name: screenshot-api
    ports:
      - "192.168.1.9:80:8080"
    restart: unless-stopped
    environment:
      - GIN_MODE=release
    mem_limit: 1g
    mem_reservation: 512m
    cpus: 1.0
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
